# --- Core Application ---
spring.application.name=api-make-v1-notification
server.servlet.context-path=/notification
spring.profiles.active=local
spring.main.allow-circular-references=true
spring.output.ansi.enabled=ALWAYS

# --- Database & JPA ---
spring.datasource.url=jdbc:postgresql://localhost:5432/master
spring.datasource.username=makewithsameer
spring.datasource.password=Ammi@123!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Hikari CP ---
spring.datasource.hikari.pool-name=HikariPool-Notification
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=20

# --- Kafka & EMQX ---
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.topic.name=notification
emqx.auth.enabled=true

# --- Elasticsearch ---
elasticsearch.enabled=true
elasticsearch.host=localhost
elasticsearch.port=9200
elasticsearch.index.name=notification-logs

# --- Logging Flags (Custom) ---
notification.logging.db.enabled=true
notification.logging.elastic.enabled=true

# --- Logging Levels ---
logging.level.root=INFO
logging.level.com.make.application=DEBUG
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n