spring.application.name=api-dev-v1-notification
# PostgreSQL Config
spring.datasource.url=jdbc:postgresql://localhost:5432/master
spring.datasource.username=devwithsameer
spring.datasource.password=Ammi@123!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.main.allow-circular-references=true
spring.profiles.active=local
# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
rest.client.enabled=false

gateway.service.url=DEFAULT
security.scheme.enabled=false
kafka.topic.name=notification
# Swagger Authentication
swagger.username=admin
swagger.password=admin123

emqx.topic.name=DEFAULT
emqx.user.name=DEFAULT
emqx.password=DEFAULT
emqx.broker.url=DEFAULT
emqx.producer.client.id=DEFAULT
emqx.auth.enabled=true

spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Elasticsearch Configuration

elasticsearch.enabled=true
elasticsearch.host=localhost
elasticsearch.port=9200
elasticsearch.auth.enabled=false
elasticsearch.username=
elasticsearch.password=
elasticsearch.index.name=notification-logs

# Tenant Interceptor Configuration
tenant.ignore.paths=/api/v3/api-docs,/api/actuator/health,/api/actuator/prometheus,/swagger-ui,/open,/v3/api-docs/swagger-config,/v3/api-docs

# Enable ANSI Colors
spring.output.ansi.enabled=ALWAYS

# Colorful Logging Pattern
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n

# Log levels
logging.level.root=INFO
logging.level.com.dev.application=DEBUG
logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=DEBUG